# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Wechaty Official Blog
email: dev@wechaty.io
description: > # this means to ignore newlines until "baseurl:"
  Wechaty is a Easy to Use ChatBot FrameWork 
  which can help you write The World's Smallest ChatBot 
  in JavaScript
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.wechaty.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: WechatyDev
github_username:  Wechaty
author: Wechaty

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-gist
exclude:
  - Gemfile
  - Gemfile.lock

disqus:
  shortname: "wechaty"

google_analytics: UA-88739146-1
